from pathlib import Path

BASE_DIR = Path("data_instagram")
STATE_FILE = "ig_state.json"
OCR_LANG = "spa"
TESSERACT_CONFIG = "--oem 3 --psm 6"
REGISTRY_DB = BASE_DIR / "registry.sqlite3"
ANALYSIS_SUFFIX = ".analysis.json"
DEFAULT_LIMIT = 5
MAX_LIMIT = 200

MANUAL_LOG_FILE = BASE_DIR / "manual_run.log"
RUNTIME_LOG_FILE = BASE_DIR / "runtime.log"
EVENTS_LOG_FILE = BASE_DIR / "events.log"
SOURCE_STATE_FILE = BASE_DIR / "source_state.json"
SUMMARY_FILE = BASE_DIR / "summary_latest_posts.json"

DELAY_BETWEEN_SOURCES_MIN = 3.0
DELAY_BETWEEN_SOURCES_MAX = 6.0
DELAY_BETWEEN_POSTS_MIN = 0.0
DELAY_BETWEEN_POSTS_MAX = 0.5
DELAY_AFTER_CLICK = 0.3
DELAY_AFTER_SCROLL = 0.5
DELAY_AFTER_KEYBOARD = 0.4
DELAY_AFTER_OVERLAY_DISMISS = 0.2
DELAY_BEFORE_SOURCE_START_MIN = 1.0
DELAY_BEFORE_SOURCE_START_MAX = 3.0
DELAY_AFTER_CONTEXT_CREATION = 1.0
DELAY_BEFORE_SOURCE_START_SCROLLING = 1.5
DELAY_AFTER_PAGE_LOAD = 2.0
DELAY_AFTER_BOOTSTRAP = 0.5
DELAY_SOURCE_COMPLETED = 1.0
DELAY_AFTER_NAVIGATE_TO_PROFILE = 1.5

MAX_RETRIES_PER_POST = 2
